# Generated by Django 2.1 on 2019-05-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'count',
            },
        ),
        migrations.CreateModel(
            name='MeetLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('user', models.ManyToManyField(to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'meetlike',
            },
        ),
        migrations.CreateModel(
            name='MeetNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='距离')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('site', models.CharField(max_length=100, null=True, verbose_name='相遇地点')),
                ('meettime', models.DateTimeField(auto_now_add=True, verbose_name='相遇时间')),
                ('friend', models.ManyToManyField(to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'meetnum',
            },
        ),
        migrations.CreateModel(
            name='MeetSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=200, null=True, verbose_name='相遇地点')),
                ('meettime', models.DateTimeField(auto_now_add=True, verbose_name='相遇时间')),
                ('nums', models.IntegerField(verbose_name='相遇次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'meetsite',
            },
        ),
        migrations.CreateModel(
            name='MeetUnlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('count', models.IntegerField(verbose_name='不喜欢次数')),
                ('gender', models.CharField(max_length=6, verbose_name='性别')),
                ('user', models.ManyToManyField(to='user.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'meetunlike',
            },
        ),
    ]
