# Generated by Django 2.1 on 2019-05-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.IntegerField(choices=[(1, '运动'), (2, '日记'), (3, '电影'), (4, '格斗'), (5, '篮球'), (6, '篮球'), (7, '旅游')], verbose_name='标签')),
            ],
            options={
                'db_table': 'lable',
            },
        ),
        migrations.CreateModel(
            name='Phono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phono', models.ImageField(upload_to='upload', verbose_name='照片')),
                ('default_display', models.BooleanField(default=True, verbose_name='默认显示')),
                ('phono_type', models.IntegerField(choices=[(1, '头像'), (2, '相册'), (3, '说说')], verbose_name='图片类型')),
            ],
            options={
                'db_table': 'phono',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friends', models.BooleanField(default=False, verbose_name='是否是好友')),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, max_length=20, unique=True, verbose_name='姓名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('age', models.IntegerField(blank=True, verbose_name='出生年月')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='纬度')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='relationship',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户B', to='user.User'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户A', to='user.User'),
        ),
        migrations.AddField(
            model_name='phono',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='lable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
